---  
 - name: Check OPatch version and update OPatch
   block:
     - shell:
        cmd: "$ORACLE_HOME/OPatch/opatch lsinventory| grep 'OPatch version' | awk -F':' '{print $2}'"
       register: opatch_version
     - name: Compare version
       set_fact: 
         current_opatch_version: "{{opatch_version.stdout|trim}}"
     - include_tasks: update_opatch.yml
       when: current_opatch_version != opatch.version
   environment:
    ORACLE_BASE: "{{ _home.oracle_base }}"
    ORACLE_HOME: "{{ _home.oracle_home }}"
   become: True
   become_user: "{{oracledb.user}}"
   when: opatch_update
 - name: Patch installation
   block:
    - include_tasks: unpack_and_check_patch.yml
    - include_tasks: apply_gi_single.yml
      when: type_install_patch == 'gi_install' 
    - include_tasks: apply_oh_patch_single.yml
      when: type_install_patch == 'db_single'  
   environment:
    ORACLE_BASE: "{{ _home.oracle_base }}"
    ORACLE_HOME: "{{ _home.oracle_home }}"   
 - name: Clean stage dir
   file:
    path: '{{ _patch.temp_dir }}/{{_patch.patch_id}}'
    state: absent
   become: true
   become_user: "{{oracledb.user}}" 

