---
- name:  Install Patch {{_patch.patch_id}}
  shell:
   cmd: '$ORACLE_HOME/OPatch/opatchauto apply {{patch.temp_dir}}/{{patch.patch_id}} -oh $ORACLE_HOME'
  register: _or_patch_installation
  ignore_errors: True
  become: true
- name: 'Check and outpup error installation of {{_patch.patch_id}}'
  include_tasks: display_stdout_or_errors.yml
  vars:
    _or_patch_debug: "{{ _or_patch_installation }}" 
  when:  _or_patch_installation.rc|default(0,true) !=0  or _or_patch_installation.stderr|default('',true)|length > 0 or display_output
       
 

