---
 - name: Backup OPatch directory
   archive:
    path: '{{oracle_home}}/OPatch/*'
    dest: '{{opatch.backup_file }}'
    format: zip
   failed_when: False
   tags: bp 
 - name: Delete OPatch folder
   file:
     path: '{{oracle_home}}/OPatch'
     state: absent 
   tags: bp
 - name: Unpack OPatch
   unarchive:  
      src:  "{{opatch.archive_url}}"   
      dest: "{{ oracle_home }}"
      remote_src: yes 
      owner: "{{oracledb.user}}"
      group: "{{oracledb.group}}"
   register:  new_opatch
   failed_when: False
   tags: unzip
 - name: Restore OPatch
   unarchive:
     src:   '{{opatch.backup_file }}'
     dest: '{{ oracle_home }}'   
     remote_src:  yes
   when: not new_opatch.changed
   register: old_opatch
 - name:  Delete OPatch backup
   file: path={{opatch.backup_file }}  state=absent
 - shell: |
      $ORACLE_HOME/OPatch/opatch version
   register: opch
 - debug: msg="{{opch.stdout_lines[0]}}"
 
   
   

    